CREATE DATABASE PRODEMY_MINI_PROJECT;

DROP TABLE IF EXISTS T_CATEGORY;
CREATE TABLE T_CATEGORY
(
    ID   INT(11)      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT
(
    ID          INT(11)      NOT NULL AUTO_INCREMENT,
    TITLE       VARCHAR(100) NOT NULL,
    PRICE       BIGINT       NOT NULL,
    IMAGE       VARCHAR(255) NOT NULL,
    CATEGORY_ID INT(11)      NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY FK_CATEGORY_PRODUCT (CATEGORY_ID) REFERENCES T_CATEGORY (ID)
);


